name: process-update
description: describe current progress 
title: "[update]: "
assignees:
  - georgetanUCSD
body:
  - type: textarea
    id: Requirement
    attributes:
      label: Requirement
    validations:
      required: true
      
  - type: textarea
    id: comment
    attributes:
      label: comment
      description: what kind of progress I made?
      placeholder: enter here!
      value: "new progress!"
    validations:
      required: false

  - type: dropdown
    id: browsers
    attributes:
      label: which part it is in Lab3?
      multiple: true
      options:
        - Part 1
        - Part 2

